### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by gndaskalova** [schneidereits/Dissertation#1]
Hey Shawn,

I tried to add this comment to your data list, but I think I only have read access, so I couldn't do a pull request, thus pasting it here! Great start on the repo!

_Note from Gergana:_ The bare ground cover also comes from the plot monitoring we do (what we call "pointframing" and is "pin drop data" in your list (we do drop pins to do it!)). Though you could also use the drone data if you were interested in larger spatial scales.

**Comment by gndaskalova** [comment]
@schneidereits the internet browser I am currently using is not cooperating well tonight, I did not mean to assign this issue to me but to you, but now I can't change it... But you get the idea!

**Comment by schneidereits** [comment]
No worries :)
I checked in my setting and couldn’t find any reason you would be able to make pull requests, but l’ll properly check tomorrow when I’m not on the phone version of GitHub.
